### ISSUE TITLE
fortios_configuration_fact.rst contains selectors which are not valid

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-ansible-dev/ansible-galaxy-fortios-sphinxdoc#3]
I have tried using `execute__tree__reboot` as the selector for `fortinet.fortios.fortios_configuration_fact`, but when I got a Traceback, and checked the code, I noticed that all the selectors containing the string `__` (e.g. `diagnose__tree___settings`, or `execute__tree__reboot`) are not listed, so there is a mismatch between the selector list and the code.

**Comment by chillancezen** [comment]
hi @JonTheNiceGuy  Jon,

do you remember what specific FortiOS version you saw `execute__tree.reboot` or `diagnose__tree.settings` in?

we generated collection based on following FortiOS major version:
https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/release.html#release-targets

I did not search them in their corresponding schema files. 

so I guess the selector you missed must be existing in earlier versions. I am not sure.

thanks,
Link

**Comment by JonTheNiceGuy** [comment]
This relates to https://github.com/fortinet-ansible-dev/fortios-ansible-generator/pull/19 which has just been merged :)

**Comment by chillancezen** [comment]
fixed in latest document: https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fortios_configuration_fact.html
