### ISSUE TITLE
Multiversions issue

### ISSUE THREAD

**Issue by tsirkin** [fortinet-ansible-dev/ansible-galaxy-fortios-sphinxdoc#4]
As noted in release notes the collection version must match the FortiOS one. 
However the specified workaround of installing the right version is not relevant in a scenario, where managing of multiple FG with different versions for multiple clients is required. 
(Ansible does not allow installing multiple versions of the same collection https://docs.ansible.com/ansible/devel/user_guide/collections_using.html#installing-an-older-version-of-a-collection).

**Comment by chillancezen** [comment]
tracked in https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/84
